// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createAuthStorage } from './storage';
import { authLog } from '@/lib/authDebugLog';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Use placeholders when env missing so the app still loads (no throw, no body overwrite)
const hasValidEnv = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && String(SUPABASE_URL).startsWith('http'));
const url = hasValidEnv ? SUPABASE_URL : 'https://placeholder.supabase.co';
const key = hasValidEnv ? SUPABASE_PUBLISHABLE_KEY : 'placeholder-key';

if (!hasValidEnv && typeof window !== 'undefined') {
  console.error(
    'Supabase: Missing or invalid VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in .env. ' +
    'Use Project URL and anon/public key from the same project. Restart dev server after changing .env.'
  );
  authLog('client', 'Missing/invalid Supabase env', { hasUrl: !!SUPABASE_URL, hasKey: !!SUPABASE_PUBLISHABLE_KEY });
}

// On OAuth callback, restore PKCE verifier from cookie to localStorage before Supabase reads it
// (Supabase uses the same storage key; this ensures the verifier is there when initialize() runs).
if (typeof window !== 'undefined' && hasValidEnv && window.location.search.includes('code=')) {
  try {
    const u = new URL(url);
    const verifierKey = `sb-${u.hostname.split('.')[0]}-auth-token-code-verifier`;
    const match = document.cookie.match(/(?:^|; )sb-pkce-code-verifier=([^;]+)/);
    if (match) {
      const val = decodeURIComponent(match[1].trim());
      localStorage.setItem(verifierKey, val);
      authLog('client', 'PKCE: restored verifier from cookie to localStorage', { key: verifierKey });
    } else {
      authLog('client', 'PKCE: no cookie on callback', { cookieLength: document.cookie.length });
    }
  } catch (e) {
    authLog('client', 'PKCE: prefill failed', e);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage backs up PKCE code_verifier in a cookie so OAuth redirect finds it
// (avoids "code verifier not found" when same-tab redirect or storage is cleared).
// detectSessionInUrl: false so only AuthCallback calls exchangeCodeForSession(code).
// Otherwise Supabase also auto-exchanges when it sees ?code=; the first exchange removes
// the verifier and the second fails with "PKCE code verifier not found".
export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: createAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'pkce',
  }
});

// Suppress AbortError warnings - these are harmless and occur during navigation
if (typeof window !== 'undefined') {
  const originalConsoleError = console.error;
  console.error = (...args: any[]) => {
    const message = args[0]?.toString() || '';
    if (message.includes('AbortError') && message.includes('signal is aborted')) {
      // Silently ignore AbortErrors from Supabase
      return;
    }
    originalConsoleError.apply(console, args);
  };
}